### ISSUE TITLE
Error when adding extension from Chrome

### ISSUE THREAD

**Issue by kezellmer** [alfovo/inspirobotNum1Fan#1]
I was trying to download the extension from Chrome (https://chrome.google.com/webstore/detail/inspirobot-1-fan-extensio/pfnbkppejibkaadinnkcapdbeedchejp?authuser=1), but encountered a "Package is invalid. Details: 'Could not load icon 'images/hal16.png' for page action.' Please don't deprive me of my inspirational quotes!

**Comment by alfovo** [comment]
@kezellmer Thank you so much for bringing this to my attention! I have reziped the image files which seems to have taken care of the problem. I am closing this ticket for now, but please feel free to create a new issue if you are still having problems 🙈
